Run requirements.sh when installing skills if exists

diff --git a/msm/msm b/msm/msm
--- a/msm/msm
+++ b/msm/msm
@@ -202,6 +202,13 @@ function install() {
         fi
       fi
     fi
+    if [[ -f "requirements.sh" ]]; then
+      echo "Setting up native environment..."
+      if ! bash requirements.sh; then
+        echo "Running requirements.sh failed!"
+        return 122
+      fi
+    fi
     echo "The ${iskill} skill has been installed!"
     echo
   done
